@startuml
title retrieve_code

class git.Repo {
    + clone_from()
}

class clone_repo {
    + clone_repo()
}

class retrieve_code {
    + retrieve_code()
}

git.Repo --> clone_repo : Uses
clone_repo --> git.Repo : Returns
clone_repo --> retrieve_code : Uses
retrieve_code --> git.Repo : Uses

@enduml
